// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IVerifier
/// @notice Interface for the Groth16 snark verifier contract generated by snarkjs.
/// @dev The concrete verifier is produced by `snarkjs zkey export solidityverifier`
///      and deployed separately. ShadePool references it via this interface.
interface IVerifier {
    /// @notice Verify a Groth16 proof against the given public inputs.
    /// @param _pA Proof element A (G1 point).
    /// @param _pB Proof element B (G2 point).
    /// @param _pC Proof element C (G1 point).
    /// @param _pubSignals Fixed-size array of 6 public signals matching the circuit.
    /// @return True if the proof is valid, false otherwise.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[6] calldata _pubSignals
    ) external view returns (bool);
}
