// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Commitments} from "./Commitments.sol";
import {TokenGuard} from "./TokenGuard.sol";
import {IVerifier} from "./IVerifier.sol";
import {PoseidonT4} from "./PoseidonT4.sol";
import {
    CommitmentPreimage,
    CommitmentCiphertext,
    ShieldCiphertext,
    ShieldRequest,
    Transaction,
    BoundParams,
    TokenData,
    UnshieldType
} from "./Types.sol";

/// @title ShadePool
/// @notice Main entry point for the Shade Protocol privacy system on Citrea.
///         Users shield (deposit) native cBTC or WcBTC into a private UTXO set
///         and later transact or unshield (withdraw) via zero-knowledge proofs.
/// @dev Inherits Commitments (Poseidon Merkle tree) and TokenGuard (cBTC wrapping).
contract ShadePool is Commitments, TokenGuard {
    // -----------------------------------------------------------------------
    //  Constants
    // -----------------------------------------------------------------------

    /// @notice Citrea mainnet chain ID, embedded in proofs to prevent cross-chain replay.
    uint64 public constant CHAIN_ID = 4114;

    // -----------------------------------------------------------------------
    //  Immutables
    // -----------------------------------------------------------------------

    /// @notice Groth16 verifier contract (generated by snarkjs).
    IVerifier public immutable verifier;

    // -----------------------------------------------------------------------
    //  Events
    // -----------------------------------------------------------------------

    /// @notice Emitted when one or more notes are shielded into the pool.
    /// @param treeNumber    The tree the commitments were inserted into.
    /// @param startPosition Leaf index of the first commitment in this batch.
    /// @param commitments   The plaintext preimages (for the shielder to verify).
    /// @param shieldCiphertext Encrypted bundles for the recipient to decrypt.
    /// @param fees          Fee amounts (reserved for future relayer integration).
    event Shield(
        uint256 treeNumber,
        uint256 startPosition,
        CommitmentPreimage[] commitments,
        ShieldCiphertext[] shieldCiphertext,
        uint256[] fees
    );

    /// @notice Emitted when a private transaction inserts new commitments.
    /// @param treeNumber    The tree the commitments were inserted into.
    /// @param startPosition Leaf index of the first commitment in this batch.
    /// @param hash          The commitment hashes (Merkle leaves).
    /// @param ciphertext    Encrypted commitment data for recipients.
    event Transact(
        uint256 treeNumber,
        uint256 startPosition,
        bytes32[] hash,
        CommitmentCiphertext[] ciphertext
    );

    /// @notice Emitted when nullifiers are marked as spent.
    /// @param treeNumber The tree the nullifiers belong to.
    /// @param nullifier  The nullifier hashes that were spent.
    event Nullified(uint16 treeNumber, bytes32[] nullifier);

    // -----------------------------------------------------------------------
    //  Constructor
    // -----------------------------------------------------------------------

    /// @param _wcBTC    Address of the WcBTC (WETH9-style) contract on Citrea.
    /// @param _verifier Address of the deployed Groth16 verifier contract.
    constructor(address _wcBTC, address _verifier) TokenGuard(_wcBTC) {
        require(_verifier != address(0), "ShadePool: zero verifier address");
        verifier = IVerifier(_verifier);
        _initMerkleTree();
    }

    // -----------------------------------------------------------------------
    //  Shield (deposit)
    // -----------------------------------------------------------------------

    /// @notice Deposit native cBTC or pre-approved WcBTC into the private pool.
    /// @dev For native cBTC: send the exact total as msg.value. Each request with
    ///      value > 0 whose preimage.value matches a portion of msg.value will be
    ///      wrapped automatically.
    ///      For WcBTC: approve this contract first, send msg.value = 0.
    /// @param requests Array of shield requests (preimage + ciphertext each).
    function shield(ShieldRequest[] calldata requests) external payable {
        uint256 count = requests.length;
        require(count > 0, "ShadePool: empty shield requests");

        bytes32[] memory leafHashes = new bytes32[](count);
        CommitmentPreimage[] memory preimages = new CommitmentPreimage[](count);
        ShieldCiphertext[] memory ciphertexts = new ShieldCiphertext[](count);
        uint256[] memory fees = new uint256[](count);

        uint256 nativeRemaining = msg.value;

        for (uint256 i = 0; i < count; i++) {
            CommitmentPreimage calldata preimage = requests[i].preimage;

            // Validate preimage fields are within the scalar field.
            require(uint256(preimage.npk) < SNARK_SCALAR_FIELD, "ShadePool: npk out of range");

            // Determine if this request uses native cBTC or pre-approved WcBTC.
            uint256 nativeForThis = 0;
            if (nativeRemaining > 0 && nativeRemaining >= preimage.value) {
                nativeForThis = preimage.value;
                nativeRemaining -= nativeForThis;
            }

            // Pull tokens in (wraps native cBTC if nativeForThis > 0).
            _handleShieldDeposit(preimage.token, preimage.value, nativeForThis);

            // Compute commitment hash = PoseidonT4(npk, tokenHash, value).
            bytes32 tokenHash = _hashTokenData(preimage.token);
            bytes32 commitmentHash = PoseidonT4.poseidon(
                [preimage.npk, tokenHash, bytes32(uint256(preimage.value))]
            );
            require(uint256(commitmentHash) < SNARK_SCALAR_FIELD, "ShadePool: commitment hash out of range");

            leafHashes[i] = commitmentHash;
            preimages[i] = preimage;
            ciphertexts[i] = requests[i].ciphertext;
            fees[i] = 0; // Reserved for future relayer fee support.
        }

        // All native cBTC should be accounted for.
        require(nativeRemaining == 0, "ShadePool: excess native value");

        // Insert commitment hashes into the Merkle tree.
        uint256 startPosition = _insertLeaves(leafHashes);

        emit Shield(treeNumber, startPosition, preimages, ciphertexts, fees);
    }

    // -----------------------------------------------------------------------
    //  Transact (private transfer / unshield)
    // -----------------------------------------------------------------------

    /// @notice Execute one or more private transactions. Each transaction proves
    ///         ownership of input notes, nullifies them, creates new output
    ///         commitments, and optionally unshields to a public address.
    /// @param transactions Array of transactions to execute.
    function transact(Transaction[] calldata transactions) external {
        uint256 count = transactions.length;
        require(count > 0, "ShadePool: empty transactions");

        for (uint256 i = 0; i < count; i++) {
            _executeTransaction(transactions[i]);
        }
    }

    // -----------------------------------------------------------------------
    //  Internal transaction execution
    // -----------------------------------------------------------------------

    function _executeTransaction(Transaction calldata txn) internal {
        BoundParams calldata bp = txn.boundParams;

        // Validate chain ID to prevent cross-chain replay.
        require(bp.chainID == CHAIN_ID, "ShadePool: wrong chain ID");

        // Validate the Merkle root is historical (belongs to the claimed tree).
        require(rootHistory[bp.treeNumber][txn.merkleRoot], "ShadePool: unknown Merkle root");

        // Check and mark nullifiers as spent.
        uint256 nullifierCount = txn.nullifiers.length;
        require(nullifierCount > 0, "ShadePool: no nullifiers");
        for (uint256 j = 0; j < nullifierCount; j++) {
            bytes32 nf = txn.nullifiers[j];
            require(!nullifiers[bp.treeNumber][nf], "ShadePool: nullifier already spent");
            nullifiers[bp.treeNumber][nf] = true;
        }

        // Build public inputs for the verifier.
        uint[6] memory publicInputs = _buildPublicInputs(txn);

        // Verify the Groth16 proof.
        bool valid = verifier.verifyProof(txn.proof.a, txn.proof.b, txn.proof.c, publicInputs);
        require(valid, "ShadePool: invalid proof");

        // Insert new commitments into the Merkle tree.
        uint256 commitmentCount = txn.commitments.length;
        if (commitmentCount > 0) {
            bytes32[] memory newLeaves = new bytes32[](commitmentCount);
            for (uint256 j = 0; j < commitmentCount; j++) {
                newLeaves[j] = txn.commitments[j];
            }

            uint256 startPosition = _insertLeaves(newLeaves);

            // Build ciphertext array for the event.
            CommitmentCiphertext[] memory ctArray = new CommitmentCiphertext[](bp.commitmentCiphertext.length);
            for (uint256 j = 0; j < bp.commitmentCiphertext.length; j++) {
                ctArray[j] = bp.commitmentCiphertext[j];
            }

            bytes32[] memory hashArray = new bytes32[](commitmentCount);
            for (uint256 j = 0; j < commitmentCount; j++) {
                hashArray[j] = txn.commitments[j];
            }

            emit Transact(treeNumber, startPosition, hashArray, ctArray);
        }

        // Emit nullifier event.
        bytes32[] memory nullifierArray = new bytes32[](nullifierCount);
        for (uint256 j = 0; j < nullifierCount; j++) {
            nullifierArray[j] = txn.nullifiers[j];
        }
        emit Nullified(bp.treeNumber, nullifierArray);

        // Handle unshield if requested.
        if (bp.unshield == UnshieldType.NORMAL) {
            // Verify the unshield preimage hashes to the last commitment.
            // This binds the preimage (recipient + amount) to the proven commitment,
            // preventing an attacker from substituting arbitrary withdrawal parameters.
            bytes32 unshieldTokenHash = _hashTokenData(txn.unshieldPreimage.token);
            bytes32 unshieldHash = PoseidonT4.poseidon(
                [txn.unshieldPreimage.npk, unshieldTokenHash, bytes32(uint256(txn.unshieldPreimage.value))]
            );
            require(
                unshieldHash == txn.commitments[txn.commitments.length - 1],
                "ShadePool: invalid unshield preimage"
            );

            // For unshield, the recipient is encoded in the npk field.
            address recipient = address(uint160(uint256(txn.unshieldPreimage.npk)));
            uint120 value = txn.unshieldPreimage.value;

            _handleUnshield(recipient, value);
        }
    }

    // -----------------------------------------------------------------------
    //  Public input construction
    // -----------------------------------------------------------------------

    /// @dev Assemble the fixed-size array of 6 public inputs expected by the verifier.
    ///      Layout: merkleRoot, boundParamsHash, nullifiers[0], nullifiers[1], commitments[0], commitments[1]
    ///      The circuit is compiled for exactly 2 inputs and 2 outputs.
    function _buildPublicInputs(Transaction calldata txn) internal pure returns (uint[6] memory inputs) {
        require(txn.nullifiers.length == 2, "ShadePool: expected exactly 2 nullifiers");
        require(txn.commitments.length == 2, "ShadePool: expected exactly 2 commitments");

        inputs[0] = uint256(txn.merkleRoot);
        inputs[1] = uint256(_hashBoundParams(txn.boundParams));
        inputs[2] = uint256(txn.nullifiers[0]);
        inputs[3] = uint256(txn.nullifiers[1]);
        inputs[4] = uint256(txn.commitments[0]);
        inputs[5] = uint256(txn.commitments[1]);
    }

    /// @dev Deterministic hash of BoundParams to a single field element.
    ///      This is matched by the off-chain circuit. Includes a hash of the
    ///      commitment ciphertexts to prevent frontrunning attacks that swap
    ///      ciphertext data.
    function _hashBoundParams(BoundParams calldata bp) internal pure returns (bytes32) {
        // Hash the commitment ciphertext array to bind it to the proof.
        bytes32 ciphertextHash = _hashCommitmentCiphertexts(bp.commitmentCiphertext);

        return bytes32(
            uint256(
                keccak256(
                    abi.encodePacked(
                        bp.treeNumber,
                        uint8(bp.unshield),
                        bp.chainID,
                        ciphertextHash
                    )
                )
            ) % SNARK_SCALAR_FIELD
        );
    }

    /// @dev Hash the commitment ciphertext array into a single bytes32.
    function _hashCommitmentCiphertexts(
        CommitmentCiphertext[] calldata cts
    ) internal pure returns (bytes32) {
        bytes memory packed;
        for (uint256 i = 0; i < cts.length; i++) {
            packed = abi.encodePacked(
                packed,
                cts[i].ciphertext[0],
                cts[i].ciphertext[1],
                cts[i].ciphertext[2],
                cts[i].ciphertext[3],
                cts[i].blindedSenderViewingKey,
                cts[i].blindedReceiverViewingKey,
                cts[i].annotationData,
                cts[i].memo
            );
        }
        return keccak256(packed);
    }

    // -----------------------------------------------------------------------
    //  Token data hashing
    // -----------------------------------------------------------------------

    /// @dev Hash token metadata into a single field element for the commitment.
    function _hashTokenData(TokenData calldata token) internal pure returns (bytes32) {
        return bytes32(
            uint256(
                keccak256(
                    abi.encodePacked(
                        uint8(token.tokenType),
                        token.tokenAddress,
                        token.tokenSubID
                    )
                )
            ) % SNARK_SCALAR_FIELD
        );
    }
}
